from enum import Enum as StrEnum

class ErrorCode(StrEnum):
    PRODUCT_CREATE_FAILED = "PRODUCT_CREATE_FAILED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED"
    USER_SVC_TIMEOUT = "USER_SERVICE_TIMEOUT"
    USER_SVC_UNAVAILABLE = "USER_SERVICE_UNAVAILABLE"
    USER_SVC_ERROR = "USER_SERVICE_ERROR"
